const dayItems = [
  {
    name: "sunday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "readReference",
      "pray",
      "playingLaptop",
      "pray",
      "dinner",
      "pray",
      "playingMobilePhone",
      "sleep",
    ],
  },
  {
    name: "monday",
    activity: [
      "pray",
      "celanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "sleep",
      "pray",
      "readReference",
      "pray",
      "dinner",
      "doingExercises",
      "pray",
      "sleep",
    ],
  },
  {
    name: "tuesday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "pray",
      "doingExercise",
      "pray",
      "playingMobilePhone",
      "pray",
      "dinner",
      "playingMobilePhone",
      "pray",
      "sleep",
    ],
  },
  {
    name: "wednesday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "readReference",
      "pray",
      "playingLaptop",
      "pray",
      "dinner",
      "pray",
      "playingMobilePhone",
      "sleep",
    ],
  },
  {
    name: "thursday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "watchingMovie",
      "pray",
      "playingMobilePhone",
      "pray",
      "dinner",
      "pray",
      "playingMobilePhone",
      "sleep",
    ],
  },
  {
    name: "friday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "playingBasketball",
      "pray",
      "watchingMovie",
      "pray",
      "playingMobilePhone",
      "pray",
      "dinner",
      "pray",
      "playingLaptop",
      "sleep",
    ],
  },
  {
    name: "saturday",
    activity: [
      "pray",
      "celanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "sleep",
      "pray",
      "pray",
      "dinner",
      "readReference",
      "doingExercises",
      "pray",
      "sleep",
    ],
  },
];

console.log(dayItems);
