const dayItems = [
  {
    id: 1,
    name: "sunday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "readReference",
      "pray",
      "playingLaptop",
      "pray",
      "dinner",
      "pray",
      "playingMobilePhone",
      "sleep",
    ],
  },
  {
    id: 2,
    name: "monday",
    activity: [
      "pray",
      "celanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "sleep",
      "pray",
      "readReference",
      "pray",
      "dinner",
      "doingExercises",
      "pray",
      "sleep",
    ],
  },
  {
    id: 3,
    name: "tuesday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "pray",
      "doingExercise",
      "pray",
      "playingMobilePhone",
      "pray",
      "dinner",
      "playingMobilePhone",
      "pray",
      "sleep",
    ],
  },
  {
    id: 4,
    name: "wednesday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "readReference",
      "pray",
      "playingLaptop",
      "pray",
      "dinner",
      "pray",
      "playingMobilePhone",
      "sleep",
    ],
  },
  {
    id: 5,
    name: "thursday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "watchingMovie",
      "pray",
      "playingMobilePhone",
      "pray",
      "dinner",
      "pray",
      "playingMobilePhone",
      "sleep",
    ],
  },
  {
    id: 6,
    name: "friday",
    activity: [
      "pray",
      "cleanBedroom",
      "breakfast",
      "playingBasketball",
      "pray",
      "watchingMovie",
      "pray",
      "playingMobilePhone",
      "pray",
      "dinner",
      "pray",
      "playingLaptop",
      "sleep",
    ],
  },
  {
    id: 7,
    name: "saturday",
    activity: [
      "pray",
      "celanBedroom",
      "breakfast",
      "playingLaptop",
      "pray",
      "sleep",
      "pray",
      "pray",
      "dinner",
      "readReference",
      "doingExercises",
      "pray",
      "sleep",
    ],
  },
];

console.log(dayItems);

const day = dayItems.find((day) => {
  return day.id == 3;
});

console.log({ day });
